NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.empdesk.empdir.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.empdesk.empdir.com-cert.pem
    OrganizationalUnitIdentifier: peer
